### ISSUE TITLE
Option Parse Issue

### ISSUE THREAD

**Issue by AdamKyle** [markprzepiora/rmmv-mrp-core#1]
Consider the following string:

```
<something description: "Hello \\c[14]World\\c[0]">

// Or, because I use wrap function and require tripple slashes:

<something description: "Hello \\\c[14]World\\\c[0]">

```

I get the error: **unexpected token 'c'**

Also consider the following:

```
<something description: "Some super duper long string that the note box then wraps like
this is going to cause issues because of unexpected token">
```

Both of these issues are thrown by underscore.strings map function, a function I don't even use. when I start at the bottom of the stack trace the issue is in your lexer stuff.

The example above will not work in note tags. IMO you should not care about the strings.

**Ideas?**

**Comment by markprzepiora** [comment]
Quoted string literals are parsed as JSON - which means they must follow the usual JSON escaping rules (same as escaping rules in most languages). This,

    "Hello \\\c[14]World\\\c[0]"

is not a valid string literal in JSON. `\\` parses to a backslash, and the `\c` that follows it is interpreted as an escape sequence - but there is no `\c` escape sequence.

Likely what you want is your first example,

    "Hello \\c[14]World\\c[0]"

This is parsed to the text

    Hello \c[14]World\c[0]
